// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		403: typeof import("./../components/ErrorMessage/403.vue")["default"];
		404: typeof import("./../components/ErrorMessage/404.vue")["default"];
		500: typeof import("./../components/ErrorMessage/500.vue")["default"];
		ColSetting: typeof import("./../components/ProTable/components/ColSetting.vue")["default"];
		ElAlert: typeof import("element-plus/es")["ElAlert"];
		ElAside: typeof import("element-plus/es")["ElAside"];
		ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
		ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
		ElButton: typeof import("element-plus/es")["ElButton"];
		ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
		ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"];
		ElCol: typeof import("element-plus/es")["ElCol"];
		ElColorPicker: typeof import("element-plus/es")["ElColorPicker"];
		ElContainer: typeof import("element-plus/es")["ElContainer"];
		ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
		ElDialog: typeof import("element-plus/es")["ElDialog"];
		ElDivider: typeof import("element-plus/es")["ElDivider"];
		ElDrawer: typeof import("element-plus/es")["ElDrawer"];
		ElDropdown: typeof import("element-plus/es")["ElDropdown"];
		ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
		ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
		ElForm: typeof import("element-plus/es")["ElForm"];
		ElFormItem: typeof import("element-plus/es")["ElFormItem"];
		ElHeader: typeof import("element-plus/es")["ElHeader"];
		ElIcon: typeof import("element-plus/es")["ElIcon"];
		ElImageViewer: typeof import("element-plus/es")["ElImageViewer"];
		ElInput: typeof import("element-plus/es")["ElInput"];
		ElMain: typeof import("element-plus/es")["ElMain"];
		ElMenu: typeof import("element-plus/es")["ElMenu"];
		ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
		ElOption: typeof import("element-plus/es")["ElOption"];
		ElPagination: typeof import("element-plus/es")["ElPagination"];
		ElRadio: typeof import("element-plus/es")["ElRadio"];
		ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
		ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
		ElSelect: typeof import("element-plus/es")["ElSelect"];
		ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
		ElSwitch: typeof import("element-plus/es")["ElSwitch"];
		ElTable: typeof import("element-plus/es")["ElTable"];
		ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
		ElTabPane: typeof import("element-plus/es")["ElTabPane"];
		ElTabs: typeof import("element-plus/es")["ElTabs"];
		ElTag: typeof import("element-plus/es")["ElTag"];
		ElTimePicker: typeof import("element-plus/es")["ElTimePicker"];
		ElTooltip: typeof import("element-plus/es")["ElTooltip"];
		ElUpload: typeof import("element-plus/es")["ElUpload"];
		ImportExcel: typeof import("./../components/ImportExcel/index.vue")["default"];
		Pagination: typeof import("./../components/ProTable/components/Pagination.vue")["default"];
		ProTable: typeof import("./../components/ProTable/index.vue")["default"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
		SearchForm: typeof import("./../components/SearchForm/index.vue")["default"];
		SearchFormItem: typeof import("./../components/SearchForm/components/SearchFormItem.vue")["default"];
		SwitchDark: typeof import("./../components/SwitchDark/index.vue")["default"];
		UploadImg: typeof import("./../components/UploadImg/index.vue")["default"];
	}
	export interface ComponentCustomProperties {
		vLoading: typeof import("element-plus/es")["ElLoadingDirective"];
	}
}
